version = 0.1

[default.deploy.parameters]
stack_name = "schematic-story-api"
resolve_s3 = true
s3_prefix = "schematic-story-api"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
